"""add_snapshots_and_mirrors

Revision ID: 0d90cd45b480
Revises: 869d4995aa1e
Create Date: 2026-06-20 22:53:06.112731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d90cd45b480'
down_revision: Union[str, None] = '869d4995aa1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_customer_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_analytics_original_customer_id'), 'customer_analytics', ['original_customer_id'], unique=True)
    op.create_table('daily_sales_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_daily_sales_snapshots_snapshot_date'), 'daily_sales_snapshots', ['snapshot_date'], unique=True)
    op.create_table('order_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_order_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_snapshots_original_order_id'), 'order_snapshots', ['original_order_id'], unique=False)
    op.create_index(op.f('ix_order_snapshots_snapshot_date'), 'order_snapshots', ['snapshot_date'], unique=False)
    op.create_table('orders_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_order_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_analytics_original_order_id'), 'orders_analytics', ['original_order_id'], unique=True)
    op.create_table('payment_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_payment_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_snapshots_original_payment_id'), 'payment_snapshots', ['original_payment_id'], unique=False)
    op.create_index(op.f('ix_payment_snapshots_snapshot_date'), 'payment_snapshots', ['snapshot_date'], unique=False)
    op.create_table('payments_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_payment_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_analytics_original_payment_id'), 'payments_analytics', ['original_payment_id'], unique=True)
    op.create_table('reservation_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_reservation_id', sa.Integer(), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.Column('snapshot_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservation_snapshots_original_reservation_id'), 'reservation_snapshots', ['original_reservation_id'], unique=False)
    op.create_index(op.f('ix_reservation_snapshots_snapshot_date'), 'reservation_snapshots', ['snapshot_date'], unique=False)
    op.create_table('reservations_analytics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('original_reservation_id', sa.Integer(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reservations_analytics_original_reservation_id'), 'reservations_analytics', ['original_reservation_id'], unique=True)
    op.create_table('order_versions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('changed_by', sa.Integer(), nullable=True),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('change_type', sa.String(length=50), nullable=False),
    sa.Column('old_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_order_versions_changed_at'), 'order_versions', ['changed_at'], unique=False)
    op.create_index(op.f('ix_order_versions_order_id'), 'order_versions', ['order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_order_versions_order_id'), table_name='order_versions')
    op.drop_index(op.f('ix_order_versions_changed_at'), table_name='order_versions')
    op.drop_table('order_versions')
    op.drop_index(op.f('ix_reservations_analytics_original_reservation_id'), table_name='reservations_analytics')
    op.drop_table('reservations_analytics')
    op.drop_index(op.f('ix_reservation_snapshots_snapshot_date'), table_name='reservation_snapshots')
    op.drop_index(op.f('ix_reservation_snapshots_original_reservation_id'), table_name='reservation_snapshots')
    op.drop_table('reservation_snapshots')
    op.drop_index(op.f('ix_payments_analytics_original_payment_id'), table_name='payments_analytics')
    op.drop_table('payments_analytics')
    op.drop_index(op.f('ix_payment_snapshots_snapshot_date'), table_name='payment_snapshots')
    op.drop_index(op.f('ix_payment_snapshots_original_payment_id'), table_name='payment_snapshots')
    op.drop_table('payment_snapshots')
    op.drop_index(op.f('ix_orders_analytics_original_order_id'), table_name='orders_analytics')
    op.drop_table('orders_analytics')
    op.drop_index(op.f('ix_order_snapshots_snapshot_date'), table_name='order_snapshots')
    op.drop_index(op.f('ix_order_snapshots_original_order_id'), table_name='order_snapshots')
    op.drop_table('order_snapshots')
    op.drop_index(op.f('ix_daily_sales_snapshots_snapshot_date'), table_name='daily_sales_snapshots')
    op.drop_table('daily_sales_snapshots')
    op.drop_index(op.f('ix_customer_analytics_original_customer_id'), table_name='customer_analytics')
    op.drop_table('customer_analytics')
    # ### end Alembic commands ###
