"""phase2_enhancements

Revision ID: b34b316aedff
Revises: 001_initial
Create Date: 2026-06-20 22:25:20.534545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b34b316aedff'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=500), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token'), 'refresh_tokens', ['token'], unique=True)
    op.create_table('reservations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('customer_name', sa.String(length=100), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('customer_phone', sa.String(length=20), nullable=False),
    sa.Column('table_id', sa.Integer(), nullable=True),
    sa.Column('reservation_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'SEATED', 'COMPLETED', 'CANCELLED', 'NO_SHOW', name='reservationstatus'), nullable=False),
    sa.Column('source', sa.Enum('WEB', 'CALL', 'WALK_IN', name='reservationsource'), nullable=False),
    sa.Column('coupon_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['coupon_id'], ['coupons.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['table_id'], ['tables.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column('coupons', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.drop_constraint('coupons_code_key', 'coupons', type_='unique')
    op.drop_index('ix_coupons_code', table_name='coupons')
    op.create_index(op.f('ix_coupons_code'), 'coupons', ['code'], unique=True)
    op.drop_constraint('customers_email_key', 'customers', type_='unique')
    op.drop_index('ix_customers_email', table_name='customers')
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=True)
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.alter_column('order_items', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'line_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'kitchen_status',
               existing_type=postgresql.ENUM('TO_COOK', 'PREPARING', 'COMPLETED', name='kitchenstatus'),
               nullable=False,
               existing_server_default=sa.text("'TO_COOK'::kitchenstatus"))
    op.execute("CREATE TYPE ordertype AS ENUM ('DINE_IN', 'TAKEAWAY', 'PARCEL', 'SELF_ORDER')")
    op.add_column('orders', sa.Column('order_type', sa.Enum('DINE_IN', 'TAKEAWAY', 'PARCEL', 'SELF_ORDER', name='ordertype'), server_default='DINE_IN', nullable=False))
    op.add_column('orders', sa.Column('pickup_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('orders', sa.Column('delivery_notes', sa.String(length=500), nullable=True))
    op.add_column('orders', sa.Column('customer_phone', sa.String(length=20), nullable=True))
    op.add_column('orders', sa.Column('customer_name', sa.String(length=100), nullable=True))
    op.alter_column('orders', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SENT_TO_KITCHEN', 'PREPARING', 'READY', 'PAID', 'CANCELLED', name='orderstatus'),
               nullable=False,
               existing_server_default=sa.text("'DRAFT'::orderstatus"))
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('orders_order_number_key', 'orders', type_='unique')
    op.drop_index('ix_orders_order_number', table_name='orders')
    op.create_index(op.f('ix_orders_order_number'), 'orders', ['order_number'], unique=True)
    op.alter_column('payment_methods', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'),
               nullable=False,
               existing_server_default=sa.text("'PENDING'::paymentstatus"))
    op.alter_column('pos_sessions', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('pos_sessions', 'opening_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('pos_sessions', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='sessionstatus'),
               nullable=False,
               existing_server_default=sa.text("'OPEN'::sessionstatus"))
    op.alter_column('products', 'tax_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('promotions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('tables', 'seat_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('4'))
    op.alter_column('tables', 'active_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'OCCUPIED', 'RESERVED', name='tablestatus'),
               nullable=False,
               existing_server_default=sa.text("'AVAILABLE'::tablestatus"))
    op.drop_constraint('tables_unique_token_key', 'tables', type_='unique')
    op.drop_index('ix_tables_unique_token', table_name='tables')
    op.create_index(op.f('ix_tables_unique_token'), 'tables', ['unique_token'], unique=True)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_tables_unique_token'), table_name='tables')
    op.create_index('ix_tables_unique_token', 'tables', ['unique_token'], unique=False)
    op.create_unique_constraint('tables_unique_token_key', 'tables', ['unique_token'])
    op.alter_column('tables', 'active_status',
               existing_type=postgresql.ENUM('AVAILABLE', 'OCCUPIED', 'RESERVED', name='tablestatus'),
               nullable=True,
               existing_server_default=sa.text("'AVAILABLE'::tablestatus"))
    op.alter_column('tables', 'seat_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('4'))
    op.alter_column('promotions', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.alter_column('products', 'tax_percentage',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('pos_sessions', 'status',
               existing_type=postgresql.ENUM('OPEN', 'CLOSED', name='sessionstatus'),
               nullable=True,
               existing_server_default=sa.text("'OPEN'::sessionstatus"))
    op.alter_column('pos_sessions', 'opening_balance',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('pos_sessions', 'opened_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('payments', 'status',
               existing_type=postgresql.ENUM('PENDING', 'SUCCESS', 'FAILED', name='paymentstatus'),
               nullable=True,
               existing_server_default=sa.text("'PENDING'::paymentstatus"))
    op.alter_column('payment_methods', 'enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_index(op.f('ix_orders_order_number'), table_name='orders')
    op.create_index('ix_orders_order_number', 'orders', ['order_number'], unique=False)
    op.create_unique_constraint('orders_order_number_key', 'orders', ['order_number'])
    op.alter_column('orders', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('orders', 'total_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'subtotal',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('orders', 'status',
               existing_type=postgresql.ENUM('DRAFT', 'SENT_TO_KITCHEN', 'PREPARING', 'READY', 'PAID', 'CANCELLED', name='orderstatus'),
               nullable=True,
               existing_server_default=sa.text("'DRAFT'::orderstatus"))
    op.alter_column('orders', 'table_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('orders', 'customer_name')
    op.drop_column('orders', 'customer_phone')
    op.drop_column('orders', 'delivery_notes')
    op.drop_column('orders', 'pickup_time')
    op.drop_column('orders', 'order_type')
    op.execute("DROP TYPE ordertype")
    op.alter_column('order_items', 'kitchen_status',
               existing_type=postgresql.ENUM('TO_COOK', 'PREPARING', 'COMPLETED', name='kitchenstatus'),
               nullable=True,
               existing_server_default=sa.text("'TO_COOK'::kitchenstatus"))
    op.alter_column('order_items', 'line_total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'discount_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'tax_amount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True,
               existing_server_default=sa.text("'0'::numeric"))
    op.alter_column('order_items', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.create_index('ix_customers_email', 'customers', ['email'], unique=False)
    op.create_unique_constraint('customers_email_key', 'customers', ['email'])
    op.drop_index(op.f('ix_coupons_code'), table_name='coupons')
    op.create_index('ix_coupons_code', 'coupons', ['code'], unique=False)
    op.create_unique_constraint('coupons_code_key', 'coupons', ['code'])
    op.alter_column('coupons', 'is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_table('reservations')
    op.drop_index(op.f('ix_refresh_tokens_token'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    # ### end Alembic commands ###
