"""Add StoreSetting model

Revision ID: f98d6201b3ea
Revises: 0d90cd45b480
Create Date: 2026-06-21 04:25:31.855281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f98d6201b3ea'
down_revision: Union[str, None] = '0d90cd45b480'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('store_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('store_name', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('online_ordering_enabled', sa.Boolean(), nullable=False),
    sa.Column('pay_at_counter_enabled', sa.Boolean(), nullable=False),
    sa.Column('splash_background_color', sa.String(length=20), nullable=True),
    sa.Column('splash_image_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('store_settings')
    # ### end Alembic commands ###
